Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -13,6 +13,15 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      - name: Check WakaTime API Key Presence
+        run: |
+          if [ -z "${{ secrets.WAKATIME_API_KEY }}" ]; then
+            echo "Secret WAKATIME_API_KEY is missing or empty!"
+            exit 1
+          else
+            echo "Secret WAKATIME_API_KEY is set!"
+          fi
+
       - name: Update README with WakaTime Stats
         uses: athul/waka-readme@master
         env:
